/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Messages.h
  Source: Messages.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#ifndef DDSC_MESSAGES_H
#define DDSC_MESSAGES_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CycloneBridgeData_IntNumber
{
  uint32_t int_num;
} CycloneBridgeData_IntNumber;

extern const dds_topic_descriptor_t CycloneBridgeData_IntNumber_desc;

#define CycloneBridgeData_IntNumber__alloc() \
((CycloneBridgeData_IntNumber*) dds_alloc (sizeof (CycloneBridgeData_IntNumber)));

#define CycloneBridgeData_IntNumber_free(d,o) \
dds_sample_free ((d), &CycloneBridgeData_IntNumber_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_MESSAGES_H */
