/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Messages.c
  Source: Messages.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "Messages.h"

static const uint32_t CycloneBridgeData_IntNumber_ops [] =
{
  /* IntNumber */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (CycloneBridgeData_IntNumber, int_num),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CycloneBridgeData_IntNumber_desc =
{
  .m_size = sizeof (CycloneBridgeData_IntNumber),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CycloneBridgeData::IntNumber",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = CycloneBridgeData_IntNumber_ops,
  .m_meta = ""
};

